name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group if not exists
        run: |
          az group create --name crypto-pilot-rg-dev --location uksouth

      - name: Deploy Bicep
        id: deploy_bicep
        run: |
          az deployment group create \
            --resource-group crypto-pilot-rg-dev \
            --template-file .github/workflows/main.bicep \
            --parameters \
              sqlAdminLogin='${{ secrets.SQL_ADMIN_LOGIN }}' \
              sqlAdminPassword='${{ secrets.SQL_ADMIN_PASSWORD }}' \
            --output json > bicep_output.json
        # Save output for next step

      - name: Get function app name from Bicep output
        id: get_funcapp_name
        run: |
          echo "FUNCTION_APP_NAME=$(jq -r '.properties.outputs.functionAppName.value' bicep_output.json)" >> $GITHUB_ENV

      - name: Get SQL server and database names from Bicep output
        id: get_sql_names
        run: |
          echo "SQL_SERVER_NAME=$(jq -r '.properties.outputs.sqlServerName.value' bicep_output.json)" >> $GITHUB_ENV
          echo "SQL_DATABASE_NAME=$(jq -r '.properties.outputs.sqlDatabaseName.value' bicep_output.json)" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Azure Function
        run: |
          dotnet publish ./Crypto.Pylot.Functions/Crypto_Pylot_Functions.csproj -c Release -o ./publish_output

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: ./publish_output

      - name: Check if sqlcmd is installed
        id: check-sqlcmd
        shell: pwsh
        run: |
          Set-GitHubOutput 'available' ($null -ne (Get-Command sqlcmd -ErrorAction SilentlyContinue))

      - name: Install sqlcmd on Linux
        if: runner.os == 'Linux' && steps.check-sqlcmd.outputs.available != 'true'
        shell: bash
        run: |
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc
          echo '/opt/mssql-tools18/bin' >> $GITHUB_PATH

      - name: Deploy database schema
        env:
          SQL_SERVER: ${{ env.SQL_SERVER_NAME }}
          SQL_DB: ${{ env.SQL_DATABASE_NAME }}
          SQL_USER: ${{ secrets.SQL_ADMIN_LOGIN }}
          SQL_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
        run: |
          sqlcmd -S "$SQL_SERVER.database.windows.net" -d "$SQL_DB" -U "$SQL_USER" -P "$SQL_PASSWORD" -i "./Crypto.Pilot.Database/create-tables.sql"
